version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: [".:/app"]
    env_file: .env
    ports: ["8000:8000"]
    depends_on: ["db","redis"]
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-inventorydb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  celery:
    build: .
    command: celery -A config.celery.app worker -l INFO
    volumes: [".:/app"]
    env_file: .env
    depends_on: ["db","redis","web"]
  beat:
    build: .
    command: celery -A config.celery.app beat -l INFO
    volumes: [".:/app"]
    env_file: .env
    depends_on: ["db","redis"]
